name: hans_android
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - nomkl
  - numpy
  - scipy
  - opencv
  - fastapi
  - pandas
  - tqdm
  - seaborn
  - openai
  - einops
  - huggingface_hub
  - pytest
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - torchaudio
    - starlette<0.51.0
    - ultralytics
    - torchreid
    - gdown
    - tensorboard
    - mcp
    - pybelt
    - open3d
    - timm
    - wandb
    - playsound==1.2.2